### PR TITLE
ci: build re/rem with cmake

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by alfredh** [comment]
The test failed with a memory leak:



```
retest: TEST_ERR: /home/runner/work/retest/retest/src/main.c:237: (Resource temporarily unavailable [11])
mem: Memory leaks (1):
  0x56194be219b0: nrefs=1  size=40      [00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ] [................]
/home/runner/work/retest/re/build/libre.so.7(+0x42df6) [0x7f2a493aadf6] 
/home/runner/work/retest/re/build/libre.so.7(mem_alloc+0xa8) [0x7f2a493aaf2d] 
/home/runner/work/retest/re/build/libre.so.7(mutex_alloc+0x2d) [0x7f2a493c5664] 
./retest(+0x39a1d) [0x561949d97a1d] 
./retest(test_remain+0x18) [0x561949d97cdf] 
./retest(+0x542b7) [0x561949db22b7] 
./retest(test_oom+0xeb) [0x561949db2454] 
./retest(main+0x3b2) [0x561949d8f7e7] 
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f2a49019083] 
./retest(_start+0x2e) [0x561949d72f1e] 
```


the failure is not related to my change.

The memory leak also happens locally on macOS.

**Comment by sreimers** [comment]
Unsure why this happens randomly now, this should fix the mutex_alloc memory leak in remain: https://github.com/baresip/retest/pull/109

**Comment by alfredh** [comment]
this patch changes building of re/rem from make to cmake.

@sreimers please review and merge to main

**Comment by sreimers** [comment]
Thanks!

**Pull request merged**
