### PR TITLE
workflows: add run-on-arch action

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by sreimers** [comment]
Looks like the IPv6 part fails in `test_net_dst_source_addr_get`, have we already some API for detect IPv6 support at runtime?

**Comment by alfredh** [comment]
the best thing would be to have a generic API to check if a certain AF is supported,
for example:

```
bool net_af_supported(int af);
```


If you have one or more IPv6 address, then net_af_supported(AF_INET6) would return true.

**Comment by alfredh** [comment]
should we merge this to main ?

The advantage is that we get extra coverage and testing for ARM64 platforms,
but the build takes between 5-10 minutes.

Another alternative is to run this in a special branch, or with a crontab (e.g. once a week).

**Comment by sreimers** [comment]
Looks good to me, maybe we can extend this with matrix, so we have at least one 32 bit platform test?

**Comment by alfredh** [comment]
thanks, I added the script with the following combinations:

1. alpine and armv7
2. Debian 11 and aarch64
3. Fedora and S390x


S390x is Big Endian 64-bits

If the script becomes very slow or annoying, please feel free to disable it.
Also feel free to adjust the combinations in the matrix.

**Pull request merged**
