### PR TITLE
Add MbedTLS support as alternative backend to OpenSSL

### PR DESCRIPTION
**Pull request by widgetii**
CI tested against my own fork https://github.com/widgetii/re/actions/runs/3017594409 , and it seems everything works as should

### CODE REVIEW

**Comment by alfredh** [comment]
hi,

is there any updates about the Mbed TLS patch ?


Alfred

**Comment by widgetii** [comment]
Ball is still on your side, this should be merged first then in libre PR will be rebased

**Comment by sreimers** [comment]
We have a dependency management, if the PR title is equal this is build against your other PR. We can test and merge this together if ready.

**Comment by widgetii** [comment]
Then feel free to rebase original PR by yourself, last time I've checked it locally all tests passed

**Comment by sreimers** [comment]
Unsure what you mean, how we should rebase your PR branch? https://github.com/widgetii/re/tree/mbedtls from https://github.com/baresip/re/pull/494

**Comment by widgetii** [comment]
I mean this task https://github.com/baresip/re/pull/494#issuecomment-1236089849
`could you please rebase on top of HEAD ?`

Everything else is done

**Pull request closed without merging**
