### PR TITLE
sa: fix valgrind warning on 32-bits

### PR DESCRIPTION
**Pull request by alfredh**
fix for https://github.com/baresip/retest/issues/98

### CODE REVIEW

**Comment by sreimers** [comment]
I wonder if this is a bug in re_snprintf too? It should not write more than `size` bytes including the `\0`? Have we to investigate further?

**Comment by alfredh** [comment]
```
DESCRIPTION
     The memcpy() function copies n bytes from memory area src to memory area dst.  If dst and src overlap,
     behavior is undefined.  Applications in which dst and src might overlap should use memmove(3) instead.
```

In this case, the printf output buffer and the first argument is the same variable, hence the overlap.

If memcpy is copying one byte at a time, overwriting the source buffer, it might work by chance.

But if the dst pointer start running faster than the source ptr, it will not work.

The fix in retest is to split one buffer into two buffers, I dont like to reuse 1 variable
for different things.

Overlapping buffers is not allowed with snprintf():


```
#include <re.h>


int main(void)
{
	char buf[128] = "hello";

	snprintf(buf, sizeof(buf), "%s", buf);

	printf("buf: '%s'\n", buf);
}


alfredh@debian:~/git/re$ make test
  CC      test.o
test.c: In function ‘main’:
test.c:8:2: warning: ‘snprintf’ argument 4 overlaps destination object ‘buf’ [-Wrestrict]
    8 |  snprintf(buf, sizeof(buf), "%s", buf);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.c:6:7: note: destination object referenced by ‘restrict’-qualified argument 1 was declared here
    6 |  char buf[128] = "hello";
      |       ^~~
  LD      test
```

**Comment by sreimers** [comment]
I see, I wonder if we can add a overlap warning with restrict type qualifier too in `re_snprintf`.

**Comment by sreimers** [comment]
Ok with PR https://github.com/baresip/re/pull/438 we get also a warning with modern gcc here:
```c
/home/runner/work/re/retest/src/sa.c: In function ‘test_sa_pton_linklocal’:
/home/runner/work/re/retest/src/sa.c:374:21: warning: passing argument 1 to ‘restrict’-qualified parameter aliases with argument 4 [-Wrestrict]
  374 |         re_snprintf(test_ipv6ll_scope, sizeof(test_ipv6ll_scope), "%s%s",
      |                     ^~~~~~~~~~~~~~~~~
  375 |                     test_ipv6ll_scope, ifname);
      |                     ~~~~~~~~~~~~~~~~~
```

**Pull request merged**
