### PR TITLE
test cmake on Windows

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by alfredh** [comment]
its almost working :)


```
LINK : warning LNK4044: unrecognized option '/lz'; ignored [D:\a\retest\retest\build\retest.vcxproj]
LINK : warning LNK4044: unrecognized option '/lpthread'; ignored [D:\a\retest\retest\build\retest.vcxproj]
LINK : warning LNK4044: unrecognized option '/lm'; ignored [D:\a\retest\retest\build\retest.vcxproj]
```


is there any way to drop these libs for Win32 ?

**Comment by alfredh** [comment]
regular tests are now working on Windows.

needs a bit more tuning and cleanup

**Comment by alfredh** [comment]
this PR should be ready to merge now.

It adds support to CI for building on Windows latest with native compiler.
Only regular tests are running for now.

@sreimers please review and merge if you agree

**Comment by sreimers** [comment]
Looks great thanks!

**Pull request merged**
